[package]
name = "lme"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
nalgebra = { version = "0.33.1", features = ["serde-serialize"] }
serde = { version = "1.0", features = ["derive"] }
n_to_n = { path = "../n_to_n" }
serde_yaml = "0.9.34"
anyhow = "1.0.91"